# 서버 포트 설정
server:
  port: 8081

# database 연동 설정
spring:
  profiles:
    active: dev
  devtools:
    livereload:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-location: classpath:/static/
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:mariadb://127.0.0.1:3304/project_ciku?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:
